const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import assert from 'node:assert/strict';
import { writeFileSync } from 'node:fs';
const base='http://127.0.0.1:3029';
const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE || undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
const results=[];
try {
for (const scenario of [{role:'member',width:390,height:844},{role:'admin',width:1440,height:1000},{role:'member',width:360,height:780}]) {
 const admin=scenario.role==='admin',email=admin?'reviewer@test.invalid':'member@test.invalid';
 const context=await browser.newContext({viewport:{width:scenario.width,height:scenario.height},serviceWorkers:'block'});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const reqs=[];let complete=false,fail=false;
 const approval=(id,status,requesterEmail,currentReviewerEmail)=>({id,title:id,type:'采购审核',project:'隔离测试',requester:'测试申请人',requesterEmail,currentReviewerEmail,createdAt:'2026-10-07',updatedAt:'2026-10-07',status,step:status==='已退回'?'补充材料':'技术顾问',summary:'隔离测试申请',owner:'测试负责人',signers:[],payload:{}});
 const approvals=[approval('需要审核的采购',complete?'已归档':'待审核','other@test.invalid',email),approval('退回本人补充的申请','已退回',email,'other@test.invalid'),approval('其他人的退回申请','已退回','other@test.invalid',email),approval('已归档申请','已归档',email,email)];
 const task=(id,title,assigneeEmail,kind='task',milestone=null)=>({id,title,project:'隔离测试',detail:'隔离测试说明',kind,status:'open',priority:'normal',assigneeName:'测试成员',assigneeEmail,dueAt:null,sourceType:'manual',sourceId:'test-member',createdByName:'测试成员',createdByEmail:email,createdAt:'',updatedAt:'2026-10-07',completedAt:null,milestone});
 const items=[task('personnel-self-expenses-test-member','确认本人消费账单（12 笔）',email),task('ordinary-task','我的项目任务',email),task('other-task','其他人的任务','other@test.invalid'),task('own-milestone','我的交付节点',email,'milestone',{deliverables:'测试交付',acceptanceCriteria:'测试标准',evidence:'',acceptedAt:null})];
 await page.route('**/api/**',async route=>{
  const u=new URL(route.request().url());reqs.push(u.pathname+u.search);
  if(route.request().method()!=='GET')return route.fulfill({status:405,json:{error:'read-only isolated fixture'}});
  if(fail&&u.pathname==='/api/approvals')return route.fulfill({status:503,json:{error:'隔离故障测试'}});
  let data={};
  if(u.pathname==='/api/session')data={registered:true,status:'active',user:{email,displayName:admin?'测试管理员':'测试成员',authProvider:'feishu'},role:admin?'project_owner':'member',isAdmin:admin,canReviewKnowledge:admin,ndaCompleted:true,needsNda:false};
  else if(u.pathname==='/api/approvals')data={approvals:approvals.map(a=>a.id==='需要审核的采购'&&complete?{...a,status:'已归档'}:a)};
  else if(u.pathname.startsWith('/api/approvals/'))data={approval:approvals.find(a=>a.id===decodeURIComponent(u.pathname.split('/').at(-1))),events:[]};
  else if(u.pathname==='/api/work-items')data={items:complete?items.filter(i=>!i.id.startsWith('personnel-self-')):items};
  else if(u.pathname==='/api/people')data={people:[],departments:[]};
  else if(u.pathname==='/api/knowledge')data={items:u.searchParams.get('scope')==='mine'?[{id:'returned-material',title:'退回的本人资料',category:'科研',status:'returned'}]:u.searchParams.get('scope')==='review'?[{id:'review-material',title:'待审核资料',category:'科研',status:'pending'}]:[],pendingCount:admin?1:0,canReviewKnowledge:admin};
  else if(u.pathname==='/api/members')data=admin?{members:[{id:'pending-member',fullName:'待准入成员',status:'pending'}],pendingCount:1}:{members:[]};
  else if(u.pathname==='/api/profile')data={profile:{}};
  else if(u.pathname.includes('conversations'))data={conversations:[]};
  else if(u.pathname.includes('members'))data={members:[]};
  else data={items:[],tasks:[],messages:[],people:[],models:[],agents:[]};
  return route.fulfill({status:200,json:data});
 });
 await page.goto(base,{waitUntil:'networkidle'});
 const expected=admin?8:6;
 await page.waitForFunction(n=>document.querySelector('.oa-global-pending .oa-pending-count')?.textContent===String(n),expected,{timeout:15000});
 assert.equal(await page.locator('.oa-pending-banner').isVisible(),true);
 assert.equal(await page.locator('.oa-global-pending').isVisible(),true);
 const box=await page.locator('.oa-global-pending').boundingBox();assert.ok(box.x>=0&&box.x+box.width<=scenario.width+1);
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No horizontal page overflow');
 await page.screenshot({path:'/tmp/oa-pending-'+scenario.role+'-'+scenario.width+'-home.png',fullPage:false});
 await page.locator('.oa-primary-navigation button').filter({hasText:'审批'}).click();
 assert.equal(await page.locator('.oa-pending-banner').isVisible(),true);
 assert.equal(await page.locator('.oa-pending-banner .oa-pending-count').textContent(),String(expected));
 await page.locator('.oa-pending-banner').click();
 await page.waitForURL('**/#todos');
 await page.getByRole('heading',{name:'待我处理',exact:true}).waitFor();
 assert.equal(await page.getByText('其他人的任务',{exact:true}).count(),0);
 assert.equal(await page.getByText('其他人的退回申请',{exact:true}).count(),0);
 assert.equal(await page.getByText('确认本人消费账单（12 笔）',{exact:true}).isVisible(),true);
 assert.equal(await page.getByText('退回的本人资料',{exact:true}).isVisible(),true);
 assert.equal(await page.getByText('我的交付节点',{exact:true}).count()>0,true);
 if(!admin)assert.ok(!reqs.includes('/api/members')&&!reqs.includes('/api/knowledge?scope=review'),'Member does not request review-only data');
 await page.screenshot({path:'/tmp/oa-pending-'+scenario.role+'-'+scenario.width+'-todos.png',fullPage:true});
 await page.reload({waitUntil:'networkidle'});await page.getByRole('heading',{name:'待我处理',exact:true}).waitFor();
 await page.locator('.approval-todo').filter({hasText:'退回本人补充的申请'}).click();
 await page.waitForFunction(()=>!!document.querySelector('[role=dialog]'));
 await page.keyboard.press('Escape');
 complete=true;
 await page.evaluate(()=>window.dispatchEvent(new Event('oa-pending-refresh')));
 await page.waitForFunction(n=>document.querySelector('.oa-global-pending .oa-pending-count')?.textContent===String(n),expected-2);
 fail=true;
 await page.evaluate(()=>window.dispatchEvent(new Event('oa-pending-refresh')));
 await page.waitForFunction(()=>document.querySelector('.oa-global-pending .oa-pending-count')?.textContent==='—');
 assert.equal(errors.length,0,errors.join('\n'));
 results.push({...scenario,count:expected,completionCount:expected-2,errors,overflow:false,deepLink:true,failedCountIsUnknown:true});
 await context.close();
}
} finally {await browser.close();}
writeFileSync('/tmp/oa-unified-todos-browser-results.json',JSON.stringify(results,null,2));
console.log(JSON.stringify(results));
